app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('press_releases/', 'Press_releasesController@index');
Route::get('press_releases/{id}', 'Press_releasesController@show');

Route::get('press_release/post', 'Press_releasesController@getPost');
Route::post('press_release/posted', array('as'=>'press_release.posted', 'uses'=>'Press_releasesController@postPost'));

Route::get('ideas/', 'IdeasController@index');
Route::get('ideas/{id}', 'IdeasController@show');

Route::get('/profile/view', 'HomeController@viewCompanyProfile' );

Route::resource('articles', 'ArticlesController');
Route::get('articles/category/{category?}', 'ArticlesController@index');

Route::resource('videos', 'VideosController');
Route::get('/logout', 'LoginController@getLogout');
Route::get('/about-us', 'HomeController@about');
Route::get('/corporate-services', 'HomeController@corporate');
Route::get('/corporate', 'HomeController@corporate');

Route::get('/terms-and-conditions', 'HomeController@toc');
Route::get('/privacy-policy', 'HomeController@privacy');
Route::get('/contact-us', array('as' => 'contact-us', 'uses'=>'HomeController@contact'));
Route::post('/feedback',  array('as' => 'feedback', 'uses'=>'HomeController@feedback'));
Route::get('/join',  array('as' => 'join', 'uses'=>'HomeController@join'));
Route::get('/options',  array('as' => 'options', 'uses'=>'HomeController@options'));

Route::get('/sign-in', 'LoginController@getIndex');
Route::post('/sign-in', 'LoginController@postIndex');

Route::get('/forgot-password', 'LoginController@getForgotPassword');
Route::post('/forgot-password', 'LoginController@postForgotPassword');

Route::get('/password/reset/{token}', 'LoginController@getResetPassword');
Route::post('/password/reset/{token}', 'LoginController@postResetPassword');

Route::get('/register', array('as'=>'get-register-basic-member', 'uses'=> 'RegisterController@getIndex'));
Route::post('/register', array('as'=>'post-register-basic-member', 'uses'=> 'RegisterController@postIndex'));

Route::get('/register/basic', array('as'=>'get-register-basic-company', 'uses'=> 'RegisterController@getBasic'));
Route::post('/register/basic', array('as'=>'post-register-basic-company', 'uses'=> 'RegisterController@postBasic'));

Route::get('/register/premium', array('as'=>'get-register-premium-company', 'uses'=> 'RegisterController@getPremium'));
Route::post('/register/premium', array('as'=>'post-register-premium-company', 'uses'=> 'RegisterController@postPremium'));

Route::get('/my-account', 'HomeController@account');

Route::get('/profile/edit',  array('as'=>'get-edit-profile', 'uses'=>'HomeController@getEditProfile'));
Route::post('/profile/update', array('as'=>'post-edit-profile', 'uses'=>'HomeController@postEditProfile'));

Route::get('/profile/edit',  array('as'=>'get-edit-profile', 'uses'=>'HomeController@getEditProfile'));

Route::get('/profile/upload-profile', array('as'=>'get-upload-profile', 'uses'=>'HomeController@getUploadProfile'));
Route::post('/profile/update-profile', array('as'=>'post-upload-profile', 'uses'=>'HomeController@postUploadProfile'));

Route::get('/profile/users', array('as'=>'get-users-profile', 'uses'=>'HomeController@getUsers'));
Route::post('/profile/save-users', array('as'=>'post-users-profile', 'uses'=>'HomeController@postUsers'));
Route::delete('/profile/users/delete/{id}', array('as'=>'profile.users.delete', 'uses'=>'HomeController@deleteUser'));

Route::get('/activate', 'RegisterController@activate');


Route::get('/upgrade', array('as'=>'get-upgrade-user', 'uses'=>'HomeController@getUpgrade'));
Route::post('/upgrade', array('as'=>'post-upgrade-user', 'uses'=>'HomeController@postUpgrade'));
Route::get('/upgrade/success', array('as'=>'get-upgrade-success', 'uses'=>'HomeController@getUpgradeSuccess'));

Route::get('/profile/interviews',  array('as'=>'get-interviews-profile', 'uses'=>'HomeController@getInterviews'));

Route::group(array ('prefix' => 'profile' ), function (){
  Route::resource('press_releases', 'Press_releasesController');
  Route::resource('company_interviews', 'Company_interviewsController');
});



Route::get('/profile/press_releases', array('as'=>'profile-press_releases', 'uses'=>'Press_releasesController@my'));
Route::get('/profile/company_interviews', array('as'=>'profile-company_interviews', 'uses'=>'Company_interviewsController@my'));
Route::post('/profile/company_interviews', array('as'=>'post-interviews-profile', 'uses'=>'HomeController@postInterviews'));
Route::post('/profile/company_interviews/{id}', array('as'=>'profile.company_interviews.update', 'uses'=>'HomeController@putInterviews'));


Route::get('/location/edit',  array('as'=>'get-edit-location', 'uses'=>'HomeController@getEditLocation'));
Route::post('/location/update',  array('as'=>'post-edit-location', 'uses'=>'HomeController@postEditLocation'));
Route::resource('companies', 'CompaniesController');

Route::get('/search', array('as'=>'get-search-jobs', 'uses'=> 'ArticlesController@search'));

Route::get('/login', array('as'=>'login',  'uses'=> 'LoginController@getIndex'));
Route::post('/login', array('as'=>'login',  'uses'=> 'LoginController@postIndex'));// function(){
  //return Redirect::to('admin/login');
//});

Route::get('/api/articles/json', 'Administration\ArticlesController@getDatatable');
Route::get('/api/categories/json', 'Administration\CategoriesController@getDatatable');
Route::get('/api/companies/json', 'Administration\CompaniesController@getDatatable');
Route::get('/api/company_interviews/json', 'Administration\Company_interviewsController@getDatatable');
Route::get('/api/company_reviews/json', 'Administration\Company_reviewsController@getDatatable');
Route::get('/api/complaints/json', 'Administration\ComplaintsController@getDatatable');
Route::get('/api/countries/json', 'Administration\CountriesController@getDatatable');
Route::get('/api/deal_sections/json', 'Administration\Deal_sectionsController@getDatatable');
Route::get('/api/ideas/json', 'Administration\IdeasController@getDatatable');
Route::get('/api/industries/json', 'Administration\IndustriesController@getDatatable');
Route::get('/api/members/json', 'Administration\MembersController@getDatatable');
Route::get('/api/pages/json', 'Administration\PagesController@getDatatable');
Route::get('/api/patent_investments/json', 'Administration\Patent_investmentsController@getDatatable');
Route::get('/api/press_releases/json', 'Administration\Press_releasesController@getDatatable');
Route::get('/api/patents/json', 'Administration\PatentsController@getDatatable');
Route::get('/api/services/json', 'Administration\ServicesController@getDatatable');
Route::get('/api/ad_banners/json', 'Administration\Ad_bannersController@getDatatable');
Route::get('/api/videos/json', 'Administration\VideosController@getDatatable');


Route::get('/api/sections/json', 'Administration\SectionsController@getDatatable');

Route::get('/register/success', array('as'=>'register.success', 'uses'=> 'RegisterController@success'));
Route::group(array ('before' => 'auth', 'prefix' => 'admin' ), function ()
{   
  Route::get('/', 'Administration\PagesController@index' );//'Firalabs\Firadmin\Controllers\DashboardController@getIndex');

  Route::get('articles/category/{category?}', 'Administration\ArticlesController@index');


  Route::put('accounts/{id}/change-password', 'Administration\AccountsController@changePassword');


  Route::get('articles/csv', 'Administration\ArticlesController@getCSV');

  Route::get('categories/csv', 'Administration\CategoriesController@getCSV');
  Route::get('companies/csv', 'Administration\CompaniesController@getCSV');
  Route::get('companies/import', 'Administration\CompaniesController@getImport');
  Route::post('companies/import', 'Administration\CompaniesController@postImport');

  Route::get('company_interviews/csv', 'Administration\Company_interviewsController@getCSV');
  Route::get('company_reviews/csv', 'Administration\Company_reviewsController@getCSV');
  Route::get('complaints/csv', 'Administration\ComplaintsController@getCSV');
  Route::get('countries/csv', 'Administration\CountriesController@getCSV');
  Route::get('deal_sections/csv', 'Administration\Deal_sectionsController@getCSV');
  Route::get('ideas/csv', 'Administration\IdeasController@getCSV');
  Route::get('industries/csv', 'Administration\IndustriesController@getCSV');
  Route::get('members/csv', 'Administration\MembersController@getCSV');
  Route::get('services/csv', 'Administration\ServicesController@getCSV');  
  Route::get('pages/csv', 'Administration\PagesController@getCSV');
  Route::get('patents/csv', 'Administration\PatentsController@getCSV');
  Route::get('press_releases/csv', 'Administration\Press_releasesController@getCSV');
  Route::get('patent_investments/csv', 'Administration\Patent_investmentsController@getCSV');
  Route::get('videos/csv', 'Administration\VideosController@getCSV');
  Route::get('sections/csv', 'Administration\SectionsController@getCSV');
  Route::get('photos/csv', 'PhotosController@getCSV');
  Route::get('sections/csv', 'Administration\SectionsController@getCSV');


  Route::resource('accounts', 'Administration\AccountsController');
  Route::resource('articles', 'Administration\ArticlesController');
  Route::resource('categories', 'Administration\CategoriesController');
  Route::resource('companies', 'Administration\CompaniesController');
  Route::resource('company_interviews', 'Administration\Company_interviewsController');
  Route::resource('company_reviews', 'Administration\Company_reviewsController');
  Route::resource('complaints', 'Administration\ComplaintsController');

app/controllers/administration/HomeController.php
<?php
namespace Administration;

use BaseController;
use View;
 

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/views/home/about.blade.php
@extends('layouts.master')
@section('main')
<style type="text/css">
	h3.title {
	    font-family: 'Open Sans Condensed',sans-serif;
	    font-size: 30px;
	    text-shadow: 0 0 1px #FFFFFF;
	    line-height: 35px;
	}

	blockquote.title {
	    font-family: 'Open Sans Condensed',sans-serif;
	    font-size: 50px;
	    text-shadow: 0 0 1px #FFFFFF;
	    color: #CCCCCC;
	    line-height: 50px;
	    text-align: center;
	}
</style>
<div class="row">
  <div class="col-md-8">
	<div class="page">
		<h1>About Us</h1>
		<p>One1info is a membership based organization that provides complete business information directory but more importantly has been proactively assisting the UAE small and medium businesses to gain access to actual economic opportunities and advancement.</p>
		<p>Through its activities, One1info continues to build a strong business relationship with its members. One1info makes every effort to develop and provide members with current and up to date information on businesses, events, opportunities and outreach programs with major corporations and public agencies in the UAE and across the globe.</p>
		<blockquote class="title">That is why One1info is truly the first and foremost point of call for all your business enquiries.....</blockquote>
		<h3 class="title">Why is One1info so DIFFERENT from the other listing directory for businesses in the United Arab Emirates?</h3>
		<p> Firstly, It provides a more comprehensive information listing than any other business directory, however, what makes One1info unique, is that it offers benefits and advantages by pro-actively marketing, promoting and seeking genuine business opportunities that translate in to profit for its members.</p>
		<h3 class="title">HOW DOES One1info HELP IT's MEMBERS?</h3>
		<p>One1info takes the time to consult with all its members, understand the nature of their business (no matter how big or small), the industry they're in and the underlying objectives for growth and profit. It also identifies the strengths and weaknesses in the members business and then refers them to its specialist team of experts and consultants from over 10 different sectors. The member gets to select 5 different experts, who then visit the member to discuss and implement a strategy to accomplish their goals effectively and efficiently. This service and all the other extensive services are completely free to all our members. </p>


	</div>
  </div>	
  <div class="col-md-4">
    @include('partials.box-get-listed')
    @include('partials.box-search-companies')
    <img src="/assets/images/tall-01.jpg" />
    
  </div>
</div>

@stop

app/views/home/contact-us.blade.php
@extends('layouts.master')
@section('main')
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKcl8AF6bZbUKLNCE9P676PIphV_IliEc&sensor=false"></script>
<script type="text/javascript" src="http://www.map-generator.org/map/iframejs/75743e6b-a325-4a82-a2aa-991c2e9f242e?key=AIzaSyCKcl8AF6bZbUKLNCE9P676PIphV_IliEc&width=300px&height=400px"></script>
<div class="row">
  <div class="col-md-8">
	<div class="page">
		<h1>Contact Us</h1>
		 <blockquote>
		 	<p>Al Buraq Building,<br/>
			Floor 1, Office 12<br/>
			P.O. Box No.10044<br/>
			Ras Al Khaimah, UAE<br/><br/>

			Call-Free : 600-577775 [UAE]<br/><br/>

			Phone : +971 7 2282555<br/>
			Fax : +971 7 2260527<br/>
			Email : info@one1info.com</p>
		</blockquote>

	<h1>Email Us</h1>

	{{ Form::open(array('route' => 'feedback')) }}
	<ul>
        <li>
            {{ Form::label('Name', 'Name:') }}
            {{ Form::text('name', '', array('class'=>'input-xxlarge')) }}
            <span class="errors">{{ $errors->first('name') }}</span>
        </li>
        <li>
            {{ Form::label('Email', 'Email:') }}
            {{ Form::text('email', '', array('class'=>'input-xxlarge')) }}
            <span class="errors">{{ $errors->first('email') }}</span>
        </li>
        <li>
            {{ Form::label('Phone', 'Phone:') }}
            {{ Form::text('phone', '', array('class'=>'input-xxlarge')) }}
            <span class="errors">{{ $errors->first('phone') }}</span>
        </li>
        <li>
            {{ Form::label('country', 'Country:') }}
            {{ Form::select('country', Country::lists('name','name')) }}
        </li>
        <li>
            {{ Form::label('message', 'Message:') }}
            {{ Form::textarea('message', '', array('class'=>'input-xxlarge')) }}
            <span class="errors">{{ $errors->first('message') }}</span>
        </li>
    	<li>		
			{{ Form::submit('Send', array('class' => 'btn btn-info')) }}
    	</li>
	</ul>

	{{ Form::close() }}

	</div>
  </div>	

  <div class="col-md-4">
  <div class="well">
      <h2>Our Location</h2>
      <div class="content">
        	<div id ="mapid-75743e6b-a325-4a82-a2aa-991c2e9f242e"></div>
	<br />
	<a href="http://www.map-generator.org/75743e6b-a325-4a82-a2aa-991c2e9f242e/large-map.aspx">Enlarge Map</a>
</div>
</div>
    @include('partials.box-get-listed')
  </div>
</div>

@stop

app/views/home/corporate.blade.php
@extends('layouts.master')
@section('head')
    <link rel="stylesheet" media="screen" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/black-tie/jquery-ui.css">
@stop
@section('main')
<div class="row">
  <div class="col-md-12">
	<div class="page">
		<h1>Corporate Services</h1>
		

		<div id="va-accordion" class="va-container">
			@foreach($services as $vv)
			<h3 class="va-title">{{ $vv->name }}</h3>
			<div class="va-content">
				{{ $vv->body }}
			</div>
			@endforeach
		</div>		

		<p>&nbsp;</p>



	</div>
  </div>	

</div>
<script type="text/javascript">
	$(function() {
		$('#va-accordion').accordion({
				visibleSlices : 5,
				expandedHeight : 250,
				animOpacity : 0.1,
				contentAnimSpeed: 100
		});
	}); 
</script>
@stop

app/views/home/index.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-8">
    <div id="featured" >  
        <ul class="ui-tabs-nav">  
          <?php $flag = 0; ?>
          @foreach ($featured_articles as $article)
          <?php 
            if(count($article->photos) == 0)
              continue;
          ?>
            <li class="ui-tabs-nav-item" id="nav-fragment-{{$article->id}}"><a href="#fragment-{{$article->id}}"><span>{{ StringHelper::trimIt($article->title, 55) }}</span></a></li>  
              <?php $flag = 1;?>
            </li>
          @endforeach
        </ul>
        @foreach ($featured_articles as $article)
          <?php 
            if(count($article->photos) == 0)
              continue;
          ?>
          <div id="fragment-{{$article->id}}" class="ui-tabs-panel" style="">  
            <img src="<?php echo $article->photos->first()->getImageUrl('385','385'); ?>"  />
            <div class="info">
            <p>{{StringHelper::trimIt($article->caption, 245)}}<a class="blue-link" href="{{ url('articles', array('id'=>$article->id)) }}" >read more</a></p>  
            </div>
          </div>
        @endforeach
    </div>

    <?php echo '<div class="">';?>
    @foreach ($sections as $ii=>$section)
      <?php 
      if (($ii)%2 == 0):
        echo '</div>';
        echo '<div class="row clearfix">';
      endif;
      ?>
      <div class="niblet col-md-4">
        <h2>{{ link_to('articles/category/'.$section->name, $section->name, array('section'=>$section->id), $secure = null); }}</h2>
        <?php $flag = 0; ?> 
        @foreach($section->articles->take(4) as $article)
        <?php if ($flag == 0): ?>
        <?php if(count($article->photos) != 0):?>
        <a href="{{URL::to('articles', array($article->id))}}">
          <img class="pull-left" style="padding-right:10px;" src="<?php echo $article->photos->first()->getImageUrl('120', '90'); ?>"  />
        </a>
      <?php endif;?>
          <h3 style="margin-bottom:3px;">{{ link_to_route('articles.show', StringHelper::trimIt($article->title, 70), array($article->id)) }}</h3>
            <p><?php // substr($article->caption, 0, 305)}}...?></p>
          
          <div class="clearfix" style="margin-bottom:5px;"></div>
          <?php $flag = 1; ?>
        <?php endif; ?>
        <div class="single-element"><span>■ </span>{{ link_to_route('articles.show', StringHelper::trimIt($article->title, 48), array($article->id)) }}</div>

        @endforeach
        <div class="single-element blue-link">{{ link_to('articles/category/'.$section->name, 'view more', array('section'=>$section->id, 'class'=>'blue-link'), $secure = null); }}</div>

      </div>
    @endforeach
    {{ '</div>'}}

    <div class="row">
      <div class="col-md-8">

    <h2>{{ link_to('press_releases', 'Press Releases'); }}</h2>
    @foreach ($press_releases as $ii=>$press_release)
      <a href="{{URL::to('press_releases', array($press_release->id))}}">
            <div class="inline-holder">
              <?php if(count( $press_release->photos)>0):?>
                <img class="pull-left" style="padding-right:10px;" width="200" src="<?php echo $press_release->photos->first()->getImageUrl('385', '385'); ?>"  />
              <?php elseif (strlen($press_release->youtube_url)>0): ?>
                <img class="pull-left" style="padding-right:10px;" width="200" height="200" src="<?php echo StringHelper::thumbYoutube($press_release->youtube_url); ?>"  />
              <?php endif;?>

              <p>{{ StringHelper::trimIt($press_release->title, 60) }}</p>
            </div>
        </a>

    @endforeach
    </div>
  </div>



    <div class="row">
      <div class="col-md-8">

    <h2>{{ link_to('ideas', 'New Ideas'); }}</h2>
    @foreach ($ideas as $ii=>$idea)
      <a href="{{URL::to('ideas', array($idea->id))}}">
            <div class="inline-holder">
              <img class="pull-left" style="padding-right:10px;" width="200" src="<?php echo $idea->photos->first()->getImageUrl('385', '385'); ?>"  />
              <p>{{ StringHelper::trimIt($idea->title, 60) }}</p>
            </div>
        </a>

    @endforeach
    </div>
  </div>

    <div class="row">
      <div class="col-md-8">
        <h2>{{ link_to('videos/', 'Videos'); }}</h2>
         @foreach($videos->take(8) as $video)
         <a href="{{URL::to('videos', array($video->id))}}">
            <div class="video-holder">
              <div style="position:absolute; top:25px;left:40px;"><img src="/assets/images/play-video.png" /></div>

              <img class="pull-left" style="padding-right:10px;" src="<?php echo $video->getThumbnailUrl(); ?>" height="110" width="145" />
              <p style="margin-bottom:3px;">{{ StringHelper::trimIt($video->title, 50) }}</p>
            </div>
          </a>
        @endforeach
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
      <img src="/assets/images/box-1.jpg" />
      <img src="/assets/images/box-2.jpg" />
    </div>
    </div>


  </div>
  <div class="col-md-4">
    @include('partials.box-get-listed')
    @include('partials.box-search-companies')
    <img src="/assets/images/tall-01.jpg" />
    @foreach ($sections->take(2) as $section)
    <div class="row side-niblets">
      <div class="col-md-12">
        <h4> Latest From {{ $section->name }}</h2>
        <?php $flag = 0; ?> 
        @foreach($section->articles as $article)
          <div class="clearfix" style=" <?php echo $flag==0?'':'border-top:1px solid #cccccc; padding-top:10px;';?>"></div>
          <a href="{{URL::to('articles', array($article->id))}}">
            <img class="pull-left" style="padding-right:10px;" src="<?php echo $article->photos->first()->getImageUrl('70','50'); ?>"  />
          <div><b style="margin-bottom:3px;">{{ $article->title}}</b>
            <p>{{substr($article->caption, 0, 95)}}...</p>
          </div>
          </a>
          <?php $flag = 1;?>
 
        @endforeach
          <div class="clearfix" style="margin-bottom:5px;"></div>
      </div>
    </div>
    @endforeach
  </div>
</div>
<!-- Jumbotron -->
<script>
  $(function() {
    $("#featured").tabs({hide:{effect: "slide"}}).tabs("rotate", 5000, true);
  })
</script>

@stop

app/views/home/join.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-12">
	<div class="page">
		<div class="well col-md-5 " style="margin:10px 40px 30px 30px;">
			<h1>Company account</h1>
			<div class="content">
			    <ul>
					<li>- Appear on our business directory</li>
					<li>- Corporate services</li>
					<li>- Upload company profile and contact details</li>
					<li>- Weekly and daily newsletter</li>
					<li>- Ads banners</li>
					<li>- Post jobs</li>
					<li>- Post media, interview and press releases</li>
					<li>- Others</li>
				</ul>
				<p class="text-center">
			    	<a href="/options" class="btn btn-info" >REGISTER NOW</a>
				</p>
			</div>
		</div>

		<div class="well col-md-5 " style="margin:10px 50px 30px 30px;">
			<h1>Member Account</h1>
			<div class="content">
			    <ul>
					<li>- Benefit from our free services</li>
			    	<li>- Limited access to business directory</li>
			    	<li>- Search and apply for jobs</li>
			    	<li>- Recieve newsletter and updates</li>
			    	<li>- Others</li>
			    </ul>
			    <p class="text-center">
			    <a href="/register" class="btn btn-info" >REGISTER NOW</a>
			</p>

			</div>
		</div>
	</div>
  </div>
</div>

@stop		

app/views/home/options.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-12">
	<div class="page">
		<div class="well col-md-5 " style="margin:10px 40px 30px 30px;">
			<h1>Registered members</h1>
			<div class="content">
				<i>
				    Member in this category will have the rights to POST, and/or ACCESS the following about themselves and other members:
				</i>
			    <ul>
					<li>- Name of company</li>
					<li>- Address</li>
					<li>- Company phone number</li>
					<li>- Website</li>
					<li>- Contact person</li>
					<li>- Industry type</li>
					<li>- Type of Business (Classification)</li>
					<li>- License type</li>
					<li>- Years in Business</li>
					<li>- Number Of Employees</li>
					<li>- Location map</li>
					<li>- Brief company profile</li>
					<li>- Business activity</li>
					<li>- Media Blog (Video profile of the company)</li>
					<li>- Daily newsletter</li>
					<li>- Weekly newsletter</li>
					<li>- One1info-Discounts or Special Offerings</li>
					<li>- Job Site</li>
					<li>- 5 Free Business Consultancies</li>
					<li>- Directory Search Optimization</li>
					<li>- 2 * Free E-marketing Campaign</li>
					<li>- International Business Search</li>
					<li>- Magazine Advert</li>
				</ul>
				<p class="text-center">
			    <a href="/register/premium" class="btn btn-info" >REGISTER NOW</a>
			</p>
			</div>
		</div>
		<div class="well col-md-5 " style="margin:10px 50px 30px 30px;">
			<h1>Listed Member</h1>
			<div class="content">
			        <i>Member in this category will have the rights to POST, and/or ACCESS the following about themselves and other members:</i>
				<ul> 
					<li>- Name of Company</li>
					<li>- Address</li>
					<li>- Company phone number</li>
					<li>- Industry type</li>
					<li>- Type of Business</li>
					<li>- Years in Business</li>
					<li>- Daily newsletter</li>
					<li>- Access to Corporate Services</li>
				</ul>
				<div class="jumbo">
					FREE
				</div>
				<p class="text-center">
			    <a href="/register/basic" class="btn btn-info" >REGISTER NOW</a>
				</p>

			</div>
		</div>
	</div>
  </div>
</div>

@stop		

app/views/home/privacy.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-8">
	<div class="page">
		<h1>Privacy Policy</h1>
		<p>Details here. </p>
	</div>
  </div>	
  <div class="col-md-4">
    @include('partials.box-get-listed')
  </div>
</div>

@stop

app/views/home/toc.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-8">
	<div class="page">
		<h1>Terms and Conditions</h1>
		<p>Details here. </p>
	</div>
  </div>	
  <div class="col-md-4">
    @include('partials.box-get-listed')
  </div>
</div>

@stop

app/views/home/upgrade-success.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-12">
	<div class="page">
		<p class="status success">Thank you, your request has been received; our agents will contact you soon.</p>
	</div>
  </div>
</div>

@stop		

app/views/home/upgrade.blade.php
@extends('layouts.master')
@section('main')
<div class="row">
  <div class="col-md-12">
	<div class="page">
		<p>Kindly check the below features then press upgrade to proceed:</p>
		<div class="col-md-2"></div><div class="col-md-4" ><br/></div>
		<div class="well col-md-5 " style="margin:10px 0px 30px 30px;">
			<h1>Registered members</h1>
			<div class="content">
				<i>
				    Member in this category will have the rights to POST, and/or ACCESS the following about themselves and other members:
				</i>
			    <ul>
					<li>- Name of company</li>
					<li>- Address</li>
					<li>- Company phone number</li>
					<li>- Website</li>
					<li>- Contact person</li>
					<li>- Industry type</li>
					<li>- Type of Business (Classification)</li>
					<li>- License type</li>
					<li>- Years in Business</li>
					<li>- Number Of Employees</li>
					<li>- Location map</li>
					<li>- Brief company profile</li>
					<li>- Business activity</li>
					<li>- Media Blog (Video profile of the company)</li>
					<li>- Daily newsletter</li>
					<li>- Weekly newsletter</li>
					<li>- One1info-Discounts or Special Offerings</li>
					<li>- Job Site</li>
					<li>- 5 Free Business Consultancies</li>
					<li>- Directory Search Optimization</li>
					<li>- 2 * Free E-marketing Campaign</li>
					<li>- International Business Search</li>
					<li>- Magazine Advert</li>
				</ul>
				<p class="text-center ">
					{{ Form::open()}}
						<div class="text-center">
          					{{ Form::submit('Upgrade', array('class' => 'btn btn-info')) }}
          				</div>
			    	{{Form::close()}}
			</p>
			</div>
		</div>


	</div>
  </div>
</div>

@stop		