app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('press_releases/', 'Press_releasesController@index');
Route::get('press_releases/{id}', 'Press_releasesController@show');

Route::get('press_release/post', 'Press_releasesController@getPost');
Route::post('press_release/posted', array('as'=>'press_release.posted', 'uses'=>'Press_releasesController@postPost'));

Route::get('ideas/', 'IdeasController@index');
Route::get('ideas/{id}', 'IdeasController@show');

Route::get('/profile/view', 'HomeController@viewCompanyProfile' );

Route::resource('articles', 'ArticlesController');
Route::get('articles/category/{category?}', 'ArticlesController@index');

Route::resource('videos', 'VideosController');
Route::get('/logout', 'LoginController@getLogout');
Route::get('/about-us', 'HomeController@about');
Route::get('/corporate-services', 'HomeController@corporate');
Route::get('/corporate', 'HomeController@corporate');

Route::get('/terms-and-conditions', 'HomeController@toc');
Route::get('/privacy-policy', 'HomeController@privacy');
Route::get('/contact-us', array('as' => 'contact-us', 'uses'=>'HomeController@contact'));
Route::post('/feedback',  array('as' => 'feedback', 'uses'=>'HomeController@feedback'));
Route::get('/join',  array('as' => 'join', 'uses'=>'HomeController@join'));
Route::get('/options',  array('as' => 'options', 'uses'=>'HomeController@options'));

Route::get('/sign-in', 'LoginController@getIndex');
Route::post('/sign-in', 'LoginController@postIndex');

Route::get('/forgot-password', 'LoginController@getForgotPassword');
Route::post('/forgot-password', 'LoginController@postForgotPassword');

Route::get('/password/reset/{token}', 'LoginController@getResetPassword');
Route::post('/password/reset/{token}', 'LoginController@postResetPassword');

Route::get('/register', array('as'=>'get-register-basic-member', 'uses'=> 'RegisterController@getIndex'));
Route::post('/register', array('as'=>'post-register-basic-member', 'uses'=> 'RegisterController@postIndex'));

Route::get('/register/basic', array('as'=>'get-register-basic-company', 'uses'=> 'RegisterController@getBasic'));
Route::post('/register/basic', array('as'=>'post-register-basic-company', 'uses'=> 'RegisterController@postBasic'));

Route::get('/register/premium', array('as'=>'get-register-premium-company', 'uses'=> 'RegisterController@getPremium'));
Route::post('/register/premium', array('as'=>'post-register-premium-company', 'uses'=> 'RegisterController@postPremium'));

Route::get('/my-account', 'HomeController@account');

Route::get('/profile/edit',  array('as'=>'get-edit-profile', 'uses'=>'HomeController@getEditProfile'));
Route::post('/profile/update', array('as'=>'post-edit-profile', 'uses'=>'HomeController@postEditProfile'));

Route::get('/profile/edit',  array('as'=>'get-edit-profile', 'uses'=>'HomeController@getEditProfile'));

Route::get('/profile/upload-profile', array('as'=>'get-upload-profile', 'uses'=>'HomeController@getUploadProfile'));
Route::post('/profile/update-profile', array('as'=>'post-upload-profile', 'uses'=>'HomeController@postUploadProfile'));

Route::get('/profile/users', array('as'=>'get-users-profile', 'uses'=>'HomeController@getUsers'));
Route::post('/profile/save-users', array('as'=>'post-users-profile', 'uses'=>'HomeController@postUsers'));
Route::delete('/profile/users/delete/{id}', array('as'=>'profile.users.delete', 'uses'=>'HomeController@deleteUser'));

Route::get('/activate', 'RegisterController@activate');


Route::get('/upgrade', array('as'=>'get-upgrade-user', 'uses'=>'HomeController@getUpgrade'));
Route::post('/upgrade', array('as'=>'post-upgrade-user', 'uses'=>'HomeController@postUpgrade'));
Route::get('/upgrade/success', array('as'=>'get-upgrade-success', 'uses'=>'HomeController@getUpgradeSuccess'));

Route::get('/profile/interviews',  array('as'=>'get-interviews-profile', 'uses'=>'HomeController@getInterviews'));

Route::group(array ('prefix' => 'profile' ), function (){
  Route::resource('press_releases', 'Press_releasesController');
  Route::resource('company_interviews', 'Company_interviewsController');
});



Route::get('/profile/press_releases', array('as'=>'profile-press_releases', 'uses'=>'Press_releasesController@my'));
Route::get('/profile/company_interviews', array('as'=>'profile-company_interviews', 'uses'=>'Company_interviewsController@my'));
Route::post('/profile/company_interviews', array('as'=>'post-interviews-profile', 'uses'=>'HomeController@postInterviews'));
Route::post('/profile/company_interviews/{id}', array('as'=>'profile.company_interviews.update', 'uses'=>'HomeController@putInterviews'));


Route::get('/location/edit',  array('as'=>'get-edit-location', 'uses'=>'HomeController@getEditLocation'));
Route::post('/location/update',  array('as'=>'post-edit-location', 'uses'=>'HomeController@postEditLocation'));
Route::resource('companies', 'CompaniesController');

Route::get('/search', array('as'=>'get-search-jobs', 'uses'=> 'ArticlesController@search'));

Route::get('/login', array('as'=>'login',  'uses'=> 'LoginController@getIndex'));
Route::post('/login', array('as'=>'login',  'uses'=> 'LoginController@postIndex'));// function(){
  //return Redirect::to('admin/login');
//});

Route::get('/api/articles/json', 'Administration\ArticlesController@getDatatable');
Route::get('/api/categories/json', 'Administration\CategoriesController@getDatatable');
Route::get('/api/companies/json', 'Administration\CompaniesController@getDatatable');
Route::get('/api/company_interviews/json', 'Administration\Company_interviewsController@getDatatable');
Route::get('/api/company_reviews/json', 'Administration\Company_reviewsController@getDatatable');
Route::get('/api/complaints/json', 'Administration\ComplaintsController@getDatatable');
Route::get('/api/countries/json', 'Administration\CountriesController@getDatatable');
Route::get('/api/deal_sections/json', 'Administration\Deal_sectionsController@getDatatable');
Route::get('/api/ideas/json', 'Administration\IdeasController@getDatatable');
Route::get('/api/industries/json', 'Administration\IndustriesController@getDatatable');
Route::get('/api/members/json', 'Administration\MembersController@getDatatable');
Route::get('/api/pages/json', 'Administration\PagesController@getDatatable');
Route::get('/api/patent_investments/json', 'Administration\Patent_investmentsController@getDatatable');
Route::get('/api/press_releases/json', 'Administration\Press_releasesController@getDatatable');
Route::get('/api/patents/json', 'Administration\PatentsController@getDatatable');
Route::get('/api/services/json', 'Administration\ServicesController@getDatatable');
Route::get('/api/ad_banners/json', 'Administration\Ad_bannersController@getDatatable');
Route::get('/api/videos/json', 'Administration\VideosController@getDatatable');


Route::get('/api/sections/json', 'Administration\SectionsController@getDatatable');

Route::get('/register/success', array('as'=>'register.success', 'uses'=> 'RegisterController@success'));
Route::group(array ('before' => 'auth', 'prefix' => 'admin' ), function ()
{   
  Route::get('/', 'Administration\PagesController@index' );//'Firalabs\Firadmin\Controllers\DashboardController@getIndex');

  Route::get('articles/category/{category?}', 'Administration\ArticlesController@index');


  Route::put('accounts/{id}/change-password', 'Administration\AccountsController@changePassword');


  Route::get('articles/csv', 'Administration\ArticlesController@getCSV');

  Route::get('categories/csv', 'Administration\CategoriesController@getCSV');
  Route::get('companies/csv', 'Administration\CompaniesController@getCSV');
  Route::get('companies/import', 'Administration\CompaniesController@getImport');
  Route::post('companies/import', 'Administration\CompaniesController@postImport');

  Route::get('company_interviews/csv', 'Administration\Company_interviewsController@getCSV');
  Route::get('company_reviews/csv', 'Administration\Company_reviewsController@getCSV');
  Route::get('complaints/csv', 'Administration\ComplaintsController@getCSV');
  Route::get('countries/csv', 'Administration\CountriesController@getCSV');
  Route::get('deal_sections/csv', 'Administration\Deal_sectionsController@getCSV');
  Route::get('ideas/csv', 'Administration\IdeasController@getCSV');
  Route::get('industries/csv', 'Administration\IndustriesController@getCSV');
  Route::get('members/csv', 'Administration\MembersController@getCSV');
  Route::get('services/csv', 'Administration\ServicesController@getCSV');  
  Route::get('pages/csv', 'Administration\PagesController@getCSV');
  Route::get('patents/csv', 'Administration\PatentsController@getCSV');
  Route::get('press_releases/csv', 'Administration\Press_releasesController@getCSV');
  Route::get('patent_investments/csv', 'Administration\Patent_investmentsController@getCSV');
  Route::get('videos/csv', 'Administration\VideosController@getCSV');
  Route::get('sections/csv', 'Administration\SectionsController@getCSV');
  Route::get('photos/csv', 'PhotosController@getCSV');
  Route::get('sections/csv', 'Administration\SectionsController@getCSV');


  Route::resource('accounts', 'Administration\AccountsController');
  Route::resource('articles', 'Administration\ArticlesController');
  Route::resource('categories', 'Administration\CategoriesController');
  Route::resource('companies', 'Administration\CompaniesController');
  Route::resource('company_interviews', 'Administration\Company_interviewsController');
  Route::resource('company_reviews', 'Administration\Company_reviewsController');
  Route::resource('complaints', 'Administration\ComplaintsController');

app/models/Article.php
<?php

class Article extends Eloquent {
	protected $guarded = array();

  public function section(){
    return $this->belongsTo('Section');
  }

  public function beforeCreate() {

    return true;
    //or don't return nothing, since only a boolean false will halt the operation
  }
  
  public function photos()
  {
      return $this->morphMany('Photo', 'imageable');
  }
  
	public static $rules = array(
		'title' => 'required',
		'author' => 'required',
		'caption' => 'required',
		'body' => 'required',
    'section_id'=>'required',
    'dated'=>'',
		'is_published' => 'required',
		'created_by' => ''
	);
}

app/controllers/ArticlesController.php
<?php
use \BaseController;

class ArticlesController extends BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index($category = '')
	{
		if($category != ''):
			$section = Section::where('name', '=', $category)->first();

	    	$articles = Article::where('section_id', '=', $section->id)->paginate(15);//->get();

	    	$title = $section->name;
    	else:
    		$articles = Article::paginate(15);
    		$title = 'News';
    	endif;
		$featured_articles = $articles->take(5);

		$sections = Section::all();

		$this->layout->content =  View::make('articles.index', array('sections' => $sections, 'articles' => $articles, 'featured_articles'=>$featured_articles, 'title'=>$title));
	}

	public function search()
	{
		$articles = Article::query();//$this->job->all();
		if( Input::get('search')!=''){
			$articles = $articles->where('title', 'like', Input::get('search').'%');//$this->job->all();
		}

		$articles = $articles->get();

		return View::make('articles.list', compact('articles'));
	}


	public $active_menu = '';
  protected function setupLayout()
	{
		//Set layout view
		$this->layout = View::make('layouts.master');		
		
		//Set navigation
		//Default we don't have active menu 
		$this->layout->active_menu = $this->active_menu;	
		
		//Set javascript assets
		
		//Set application title
		$this->layout->title = 'Test';
		
	}
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
      $article = Article::find($id);
      $sections = Section::all();

      $this->layout->content =  View::make('articles.show', array('article'=>$article, 'sections'=>$sections));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        return View::make('articles.edit');
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/controllers/administration/Ad_settingsController.php
<?php
namespace Administration;

use BaseController;
use View;
use Config;
use Validator;
use Redirect;
use Input, Mail;

use Ad_setting;
use Photo, CSV, Datatables;

class Ad_settingsController extends BaseController {

	/**
	 * Ad_setting Repository
	 *
	 * @var Ad_setting
	 */
	protected $ad_setting;

	public function __construct(Ad_setting $ad_setting)
	{
		$this->ad_setting = $ad_setting;
	}

	public $active_menu = 'admin/ad_settings';

  	protected function setupLayout()
	{
		//Set layout view
		$this->layout = View::make('layouts.admin');

		//Default layout content is null
		$this->layout->content = '';
		
		//Set navigation
		$this->layout->navigation = Config::get('firadmin::navigation');
		
		//Default we don't have active menu 
		$this->layout->active_menu = $this->active_menu;	
		
		//Set javascript assets
		$this->layout->assets = Config::get('firadmin::assets');	
		
		//Set application title
		$this->layout->title = Config::get('firadmin::title');
		
		//Set project name
		$this->layout->project_name = Config::get('firadmin::project_name');
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$ad_settings = $this->ad_setting->all();

		$this->layout->content =  View::make('administration.ad_settings.index', compact('ad_settings'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content =  View::make('administration.ad_settings.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Ad_setting::$rules);

		if ($validation->passes())
		{
			$this->ad_setting->create($input);

			return Redirect::route('admin.ad_settings.index');
		}

		return Redirect::route('admin.ad_settings.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$ad_setting = $this->ad_setting->findOrFail($id);

		$this->layout->content =  View::make('administration.ad_settings.show', compact('ad_setting'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$ad_setting = $this->ad_setting->find($id);

		if (is_null($ad_setting))
		{
			return Redirect::route('ad_settings.index');
		}

		$this->layout->content =  View::make('administration.ad_settings.edit', compact('ad_setting'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Ad_setting::$rules);

		if ($validation->passes())
		{
			$ad_setting = $this->ad_setting->find($id);
			$ad_setting->update($input);

			return Redirect::route('admin.ad_settings.show', $id);
		}

		return Redirect::route('admin.ad_settings.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->ad_setting->find($id)->delete();

		return Redirect::route('admin.ad_settings.index');
	}

}

app/controllers/administration/HomeController.php
<?php
namespace Administration;

use BaseController;
use View;
 

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/views/administration/articles/create.blade.php
@extends('layouts.scaffold')

@section('main')
<script src="/packages/wysiwyg/ckeditor/ckeditor/ckeditor.js?t=C9A85WF" type="text/javascript"></script>
<div class="row-fluid">
  <div class="span12">

    <h1>Create Article</h1>
  </div>
</div>
<div class="row-fluid">
  <div class="span8">

    {{ Form::open(array('route' => 'admin.articles.store', 'enctype'=>"multipart/form-data")) }}
    <ul>
      <li>
        {{ Form::label('title', 'Title:') }}
        {{ Form::text('title', '', array('class'=>'input-xxlarge')) }}
      </li>

      <li>
        {{ Form::label('author', 'Author:') }}
        {{ Form::text('author') }}
      </li>

      <li>
        {{ Form::label('caption', 'Caption:') }}
        {{ Form::textarea('caption', '', array('class'=>'input-xxlarge')) }}
      </li>
      <li>
        {{ Form::label('images', 'Images:') }}
        <a href="javascript:void(0)" id="link-add-image" class="btn btn-small">ADD IMAGE</a>
        <div class="clearfix"></div>
        <ul id="image-upload-holder">
        </ul>
      </li>
      <li>
        {{ Form::label('section_id', 'Section:') }}
        {{ Form::select('section_id', Section::lists('name','id')) }}
      </li>
      <li>
        {{ Form::label('body', 'Body:') }}
        {{ Form::textarea('body', '') }}        
      </li>

      <li>
        {{ Form::label('is_published', 'Publish to site:') }}
        {{ Form::select('is_published', array('0'=>'Draft', '1'=>'Published' )) }}
      </li>


      <li>
        {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
      </li>
    </ul>
    {{ Form::close() }}
  </div>
</div>
<div id="image-holder-template" style="display:none;">
  <div class="well">
    <input name="photos[]" type="file" />
    {{ Form::text('captions[]') }}

    <a href="javascript:void(0)" class="btn btn-small lnk-remove-image"><i class="icon-cross"/></a>
  </div>
</div>
@if ($errors->any())
<ul>
  {{ implode('', $errors->all('<li class="error">:message</li>')) }}
</ul>
@endif
<script >
$(function(){
  CKEDITOR.replace('body', {
    toolbar: 'Basic',
    uiColor: '#9AB8F3'
});
  $('#link-add-image').click(function(){
    
    $('#image-upload-holder').append('<li>'+$('#image-holder-template').html()+'</li>');
    $(document).on('click', '.lnk-remove-image', function(){
      $(this).parents('li').first().remove();
    });
  });
});
</script>
  
@stop

app/views/administration/articles/edit.blade.php
@extends('layouts.scaffold')

@section('main')
<script src="/packages/wysiwyg/ckeditor/ckeditor/ckeditor.js?t=C9A85WF" type="text/javascript"></script>
<div class="row-fluid">
  <div class="span12">

    <h1>Edit Article</h1>
  </div>
</div>
<div class="row-fluid">
  <div class="span8">
{{ Form::model($article, array('method' => 'PATCH', 'enctype'=>"multipart/form-data", 'route' => array('admin.articles.update', $article->id))) }}
	<ul>
    <li>
      {{ Form::label('title', 'Title:') }}
      {{ Form::text('title', $article->title, array('class'=>'input-xxlarge')) }}
    </li>
    <li>
      {{ Form::label('author', 'Author:') }}
      {{ Form::text('author') }}
    </li>
    <li>
      {{ Form::label('caption', 'Caption:') }}
      {{ Form::textarea('caption', $article->caption, array('class'=>'input-xxlarge')) }}
    </li>
    <li>
      {{ Form::label('images', 'Images:') }}
      <a href="javascript:void(0)" id="link-add-image" class="btn btn-small">ADD IMAGE</a>
      <div class="clearfix"></div>
      <ul id="image-upload-holder">
      </ul>
      <p>
      @foreach($article->photos()->get() as $one_photo)
          <br/><img src="{{$one_photo->getImageUrl('100', '100')}}" >
          <input type="checkbox" name="delete_current_images[]" value="{{ $one_photo->id }}" />
          Delete?
          <br/>
      @endforeach
      </p>
    </li>
    <li>
      {{ Form::label('section_id', 'Section:') }}
      {{ Form::select('section_id', Section::lists('name','id')) }}
    </li>
    <li>
      {{ Form::label('body', 'Body:') }}
      {{ Form::textarea('body' ) }}        
    </li>
    <li>
      {{ Form::label('is_published', 'Publish to site:') }}
      {{ Form::select('is_published', array('0'=>'No', '1'=>'Yes' )) }}
    </li>
    <li>
      {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
    </li>
		<li>
			{{ Form::submit('Update', array('class' => 'btn btn-info')) }}
			{{ link_to_route('admin.articles.show', 'Cancel', $article->id, array('class' => 'btn')) }}
		</li>
	</ul>
{{ Form::close() }}
</div>
</div>
<div id="image-holder-template" style="display:none;">
  <div class="well">
    <input name="photos[]" type="file" />
    {{ Form::text('captions[]') }}

    <a href="javascript:void(0)" class="btn btn-small lnk-remove-image"><i class="icon-cross"/></a>
  </div>
</div>
@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

<script >
$(function(){
  CKEDITOR.replace('body', {
    toolbar: 'Basic',
    uiColor: '#9AB8F3'
});
  $('#link-add-image').click(function(){
    
    $('#image-upload-holder').append('<li>'+$('#image-holder-template').html()+'</li>');
    $(document).on('click', '.lnk-remove-image', function(){
      $(this).parents('li').first().remove();
    });
  });
});
</script>
  
@stop

app/views/administration/articles/index.blade.php
@extends('layouts.scaffold')

@section('main')
@if($category):
	<h1>Articles For Section {{ $category->name }}
 	{{ link_to('admin/sections', 'Back to Sections', array('class'=>'btn ')) }}
	</h1>

@else
	<h1>All Articles</h1>
@endif

<p>{{ link_to_route('admin.articles.create', 'Add new article', array(), array('class'=>'btn')) }} {{ link_to('admin/articles/csv', 'Export CSV', array('class'=>'btn')) }}</p>
<table class="table table-striped " id="datatable">
	<thead>
		<tr>
		<?php $columns = array('id'=>'ID', 'title'=>'Title', 'author'=>'Author', 'caption'=>'Caption', 'is_published'=>'Published?');
		foreach($columns as $column=>$title):
		    echo '<th>';
		    echo $title;
		    echo '</th>';
		endforeach;
		?>
		<th></th>
		</tr>
	</thead>
	<tbody>
		<td colspan="6" class="dataTables_empty">Loading data from server</td>
	</tbody>
</table>
<script type="text/javascript">

$(document).ready(function() {
    $('#datatable').dataTable( {
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "/api/articles/json",
        "fnServerParams": function ( aoData ) {
         	<?php echo $category!=null?' aoData.push( { "name": "category", "value": "'.$category->name.'" } );':''; ?>            
        }
    } );
} );
</script>
@stop

app/views/administration/articles/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Article</h1>

<p>{{ link_to_route('admin.articles.index', 'Return to all articles') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Title</th>
				<th>Author</th>
				<th>Caption</th>
				<th>Body</th>
				<th>Is_published</th>
				<th>Created_by</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $article->title }}}</td>
					<td>{{{ $article->author }}}</td>
					<td>{{{ $article->caption }}}</td>
					<td>{{{ $article->body }}}</td>
					<td>{{{ $article->is_published }}}</td>
					<td>{{{ $article->created_by }}}</td>
                    <td>{{ link_to_route('admin.articles.edit', 'Edit', array($article->id), array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('admin.articles.destroy', $article->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
		</tr>
	</tbody>
</table>

@stop